name: 🚀 Deploy para Render

on:
  push:
    branches:
      - master  # ou main, se for o nome do seu branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout do código
        uses: actions/checkout@v3

      - name: 📡 Chamar Deploy Hook da Render
        run: |
          curl "$RENDER_DEPLOY_HOOK"

        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
